export interface MenuItem {
  id: string;
  name: string;
  price?: number;
  halfPrice?: number;
  fullPrice?: number;
  unit?: string;
  image: string;
  description: string;
  category: string;
  popularity?: number;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  slug: string;
  image: string;
}

export const categories: Category[] = [
  { id: 'chicken', name: 'Non-Veg Main Course (Chicken)', icon: '🍗', slug: 'chicken', image: 'https://i.ibb.co/jkKJS4T8/Whats-App-Image-2026-04-04-at-12-46-16.jpg' },
  { id: 'fish', name: 'Fish', icon: '🐟', slug: 'fish', image: 'https://i.ibb.co/twFjF016/Whats-App-Image-2026-04-04-at-13-04-56.jpg' },
  { id: 'mutton', name: 'Mutton', icon: '🥩', slug: 'mutton', image: 'https://i.ibb.co/Vc8YZ2VQ/Whats-App-Image-2026-04-04-at-20-29-26.jpg' },
  { id: 'egg', name: 'Egg Special', icon: '🥚', slug: 'egg', image: 'https://i.ibb.co/ycbd9s0C/Whats-App-Image-2026-04-04-at-12-50-15.jpg' },
  { id: 'veg', name: 'Veg Main Course', icon: '🥗', slug: 'veg', image: 'https://i.ibb.co/tTKHfMmQ/Whats-App-Image-2026-04-04-at-13-08-36.jpg' },
  { id: 'roti', name: 'Roti / Bread', icon: '🍞', slug: 'roti', image: 'https://i.ibb.co/jkrdM7gn/Whats-App-Image-2026-04-04-at-13-17-20.jpg' },
  { id: 'rice', name: 'Rice', icon: '🍚', slug: 'rice', image: 'https://i.ibb.co/xqsmkqFG/Whats-App-Image-2026-04-04-at-21-49-10.jpg' },
  { id: 'starters', name: 'Starters', icon: '🍟', slug: 'starters', image: 'https://i.ibb.co/ymF5ynBh/Whats-App-Image-2026-04-04-at-21-33-04.jpg' },
  { id: 'thali', name: 'Thali', icon: '🍛', slug: 'thali', image: 'https://i.ibb.co/ynRRTkJg/Whats-App-Image-2026-04-04-at-20-47-33.jpg' },
  { id: 'sweets', name: 'Sweet Items', icon: '🍬', slug: 'sweets', image: 'https://i.ibb.co/QjX5KDbt/Whats-App-Image-2026-04-04-at-20-12-22.jpg' },
  { id: 'combo', name: 'Combo', icon: '🧺', slug: 'combo', image: 'https://i.ibb.co/5Xh0fRFS/Whats-App-Image-2026-04-04-at-21-20-56.jpg' },
  { id: 'mithilanchal', name: 'Mithilanchal Special', icon: '🌾', slug: 'mithilanchal', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800' },
  { id: 'special-thali', name: 'Special Thali', icon: '⭐', slug: 'special-thali', image: 'https://i.ibb.co/3yht8jZz/Whats-App-Image-2026-04-04-at-20-48-20.jpg' },
];

export const menuItems: MenuItem[] = [
  // Chicken
  { id: 'c1', category: 'chicken', name: 'Chicken Curry (8 Piece)', price: 550, image: 'https://i.ibb.co/jkKJS4T8/Whats-App-Image-2026-04-04-at-12-46-16.jpg', description: 'Tender chicken pieces simmered in a rich, aromatic gravy with a blend of traditional Indian spices.', popularity: 95 },
  { id: 'c2', category: 'chicken', name: 'Chicken Curry (4 Piece)', price: 300, image: 'https://i.ibb.co/jkKJS4T8/Whats-App-Image-2026-04-04-at-12-46-16.jpg', description: 'A smaller portion of our signature chicken curry, slow-cooked to perfection in a flavorful masala.', popularity: 80 },
  { id: 'c3', category: 'chicken', name: 'Chicken Curry (1 Kg)', price: 900, image: 'https://i.ibb.co/jkKJS4T8/Whats-App-Image-2026-04-04-at-12-46-16.jpg', description: 'A family-sized feast of our traditional chicken curry, featuring farm-fresh chicken and hand-ground spices.', popularity: 70 },
  { id: 'c4', category: 'chicken', name: 'Butter Chicken', halfPrice: 350, fullPrice: 650, image: 'https://i.ibb.co/W4MNjbQ0/Whats-App-Image-2026-04-04-at-21-28-50.jpg', description: 'Succulent chicken in a velvety tomato-butter sauce, finished with a touch of cream and dried fenugreek.', popularity: 90 },
  { id: 'c5', category: 'chicken', name: 'Butter Chicken (1 Kg)', price: 950, image: 'https://i.ibb.co/W4MNjbQ0/Whats-App-Image-2026-04-04-at-21-28-50.jpg', description: 'Our famous creamy butter chicken in a large portion, perfect for gatherings and celebrations.', popularity: 60 },
  { id: 'c6', category: 'chicken', name: 'Kadhai Chicken', halfPrice: 350, fullPrice: 650, image: 'https://i.ibb.co/G4N4SvMC/Whats-App-Image-2026-04-04-at-21-30-49.jpg', description: 'Bold and spicy chicken cooked with fresh bell peppers and onions in a traditional iron wok.', popularity: 85 },
  { id: 'c7', category: 'chicken', name: 'Chicken Special Curry (1 Kg)', price: 950, image: 'https://i.ibb.co/jkKJS4T8/Whats-App-Image-2026-04-04-at-12-46-16.jpg', description: 'Our chef\'s secret recipe featuring a unique blend of roasted spices and a deep, savory gravy.', popularity: 75 },
  { id: 'c8', category: 'chicken', name: 'Chicken Fry Kaleji (Half)', price: 350, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=800', description: 'Spiced chicken liver sautéed with onions, green chilies, and fresh coriander for a robust flavor.' },
  { id: 'c9', category: 'chicken', name: 'Chicken Fry', price: 60, unit: 'Piece', image: 'https://images.unsplash.com/photo-1562607394-59013bb10287?auto=format&fit=crop&q=80&w=800', description: 'Crispy, golden-brown chicken piece marinated in a zesty blend of ginger, garlic, and spices.' },
  { id: 'c10', category: 'chicken', name: 'Chicken Pota Kaleji', halfPrice: 350, fullPrice: 700, image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=800', description: 'A rustic and flavorful mix of chicken gizzard and liver, slow-cooked with traditional masalas.' },
  { id: 'c11', category: 'chicken', name: 'Chicken Kabab', halfPrice: 350, fullPrice: 700, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800', description: 'Succulent, melt-in-your-mouth chicken kababs infused with aromatic herbs and grilled to perfection.' },
  { id: 'c12', category: 'chicken', name: 'Chicken Fry Rice', halfPrice: 200, fullPrice: 400, image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=800', description: 'Wok-tossed basmati rice with tender chicken bits, crunchy vegetables, and a hint of soy and spice.' },

  // Fish
  { id: 'f1', category: 'fish', name: 'Special Fish Curry', halfPrice: 350, fullPrice: 700, image: 'https://i.ibb.co/B56GGMbM/Whats-App-Image-2026-04-04-at-08-44-09.jpg', description: 'Fresh catch cooked in a tangy mustard-based gravy with a hint of garlic and green chilies—a true Mithila delicacy.' },
  { id: 'f2', category: 'fish', name: 'Special Fish Curry (1 Kg)', price: 1000, image: 'https://i.ibb.co/Q37wB0cj/Whats-App-Image-2026-04-04-at-08-47-21-1.jpg', description: 'A generous portion of our signature fish curry, prepared with traditional techniques and local spices.' },
  { id: 'f3', category: 'fish', name: 'Fish Fry', price: 50, unit: 'Piece', image: 'https://i.ibb.co/twFjF016/Whats-App-Image-2026-04-04-at-13-04-56.jpg', description: 'Crispy, shallow-fried fish marinated in a blend of turmeric, chili, and local herbs for a perfect crunch.' },
  { id: 'f4', category: 'fish', name: 'Fish Masala Curry (Half)', price: 350, image: 'https://i.ibb.co/B56GGMbM/Whats-App-Image-2026-04-04-at-08-44-09.jpg', description: 'A spicy and robust fish curry with a thick masala base, perfect for those who love a bold flavor profile.' },

  // Mutton
  { id: 'm1', category: 'mutton', name: 'Special Mutton Curry (1 Kg)', price: 1850, image: 'https://i.ibb.co/Q7c3g5tx/Whats-App-Image-2026-04-04-at-20-33-13.jpg', description: 'Slow-cooked tender mutton in a robust gravy infused with whole spices, ginger, and garlic for a rich, deep flavor.' },
  { id: 'm2', category: 'mutton', name: 'Special Mutton Curry (4 Piece)', price: 500, image: 'https://i.ibb.co/Vc8YZ2VQ/Whats-App-Image-2026-04-04-at-20-29-26.jpg', description: 'A perfect serving of our signature mutton curry, featuring tender pieces in a flavorful, spiced gravy.' },
  { id: 'm3', category: 'mutton', name: 'Special Mutton Curry (8 Piece)', price: 950, image: 'https://i.ibb.co/Vc8YZ2VQ/Whats-App-Image-2026-04-04-at-20-29-26.jpg', description: 'A larger portion of our traditional mutton curry, prepared with hand-selected spices and slow-cooked to perfection.' },
  { id: 'm4', category: 'mutton', name: 'Special Mutton Keema Kaleji', halfPrice: 550, fullPrice: 1000, image: 'https://i.ibb.co/FLj0mZxn/Whats-App-Image-2026-04-04-at-12-47-08.jpg', description: 'A savory and hearty combination of minced mutton and liver, sautéed with a blend of aromatic spices.' },
  { id: 'm5', category: 'mutton', name: 'Mutton Chusta', price: 150, unit: 'Piece', image: 'https://i.ibb.co/prGYPDY9/Whats-App-Image-2026-04-04-at-13-01-50.jpg', description: 'A traditional delicacy featuring spiced mutton intestine, slow-cooked to achieve a unique and savory taste.' },
  { id: 'm6', category: 'mutton', name: 'Mutton Peti (Full)', price: 750, image: 'https://i.ibb.co/FLj0mZxn/Whats-App-Image-2026-04-04-at-12-47-08.jpg', description: 'A specialty cut of tender mutton, prepared in a rich and spicy gravy that highlights its natural flavors.' },
  { id: 'm7', category: 'mutton', name: 'Mutton Paya', halfPrice: 550, fullPrice: 1100, image: 'https://i.ibb.co/FLj0mZxn/Whats-App-Image-2026-04-04-at-12-47-08.jpg', description: 'Slow-cooked mutton trotters in a nutritious and flavorful broth, seasoned with traditional warming spices.' },
  { id: 'm8', category: 'mutton', name: 'Mutton Curry Family Pack', price: 1600, image: 'https://i.ibb.co/Q7c3g5tx/Whats-App-Image-2026-04-04-at-20-33-13.jpg', description: 'A generous family-sized portion of our classic mutton curry, perfect for sharing a traditional meal.' },

  // Egg
  { id: 'e1', category: 'egg', name: 'Egg Omelette', price: 200, image: 'https://i.ibb.co/RGLMchLb/Whats-App-Image-2026-04-04-at-20-53-28.jpg', description: 'A fluffy and savory egg omelette, seasoned with fresh herbs, onions, and green chilies.' },
  { id: 'e2', category: 'egg', name: 'Egg Burji', price: 220, image: 'https://i.ibb.co/MxQ0jYgf/Whats-App-Image-2026-04-04-at-20-52-41.jpg', description: 'Spiced scrambled eggs cooked with a medley of onions, tomatoes, and aromatic Indian masalas.' },
  { id: 'e3', category: 'egg', name: 'Egg Curry', halfPrice: 180, fullPrice: 350, image: 'https://i.ibb.co/ycbd9s0C/Whats-App-Image-2026-04-04-at-12-50-15.jpg', description: 'Classic hard-boiled eggs simmered in a rich and flavorful onion-tomato gravy with a blend of warm spices.' },
  { id: 'e4', category: 'egg', name: 'Egg Curry Family Pack', price: 500, image: 'https://i.ibb.co/ycbd9s0C/Whats-App-Image-2026-04-04-at-12-50-15.jpg', description: 'A generous portion of our classic egg curry, perfect for a family meal or gathering.' },
  { id: 'e5', category: 'egg', name: 'Egg Half Fry', price: 30, image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=800', description: 'Perfectly cooked sunny-side-up egg with a runny yolk, lightly seasoned with salt and pepper.' },

  // Veg
  { id: 'v1', category: 'veg', name: 'Matar Paneer', halfPrice: 180, fullPrice: 380, image: 'https://i.ibb.co/tpY1zgW1/Whats-App-Image-2026-04-04-at-13-06-29.jpg', description: 'Soft paneer cubes and sweet green peas in a mildly spiced tomato-onion gravy, a timeless North Indian favorite.', popularity: 92 },
  { id: 'v2', category: 'veg', name: 'Shahi Paneer', halfPrice: 200, fullPrice: 400, image: 'https://i.ibb.co/tTKHfMmQ/Whats-App-Image-2026-04-04-at-13-08-36.jpg', description: 'Exquisite paneer in a rich, creamy white gravy flavored with cardamom, saffron, and a hint of sweetness.', popularity: 88 },
  { id: 'v3', category: 'veg', name: 'Paneer Butter Masala', halfPrice: 220, fullPrice: 410, image: 'https://i.ibb.co/ks9rSpgm/Whats-App-Image-2026-04-04-at-21-29-28.jpg', description: 'Classic paneer dish in a smooth, buttery tomato sauce with aromatic spices and a velvety finish.', popularity: 85 },
  { id: 'v4', category: 'veg', name: 'Kadhai Paneer', halfPrice: 250, fullPrice: 450, image: 'https://i.ibb.co/k2KLJVxh/Whats-App-Image-2026-04-04-at-21-21-50.jpg', description: 'Paneer tossed with crunchy bell peppers and freshly ground spices in a traditional iron kadhai.', popularity: 82 },
  { id: 'v5', category: 'veg', name: 'Mix Veg', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/VcPb681m/Whats-App-Image-2026-04-04-at-21-17-47.jpg', description: 'A vibrant medley of seasonal vegetables sautéed with traditional Indian herbs and a touch of garam masala.', popularity: 78 },
  { id: 'v6', category: 'veg', name: 'Aloo Gobhi', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/Dgmz06bW/Whats-App-Image-2026-04-04-at-21-06-14.jpg', description: 'Home-style preparation of potatoes and cauliflower florets with turmeric, cumin, and fresh ginger.' },
  { id: 'v7', category: 'veg', name: 'Aloo Parwal', halfPrice: 180, fullPrice: 350, image: 'https://i.ibb.co/pjw5rM5Z/Whats-App-Image-2026-04-04-at-21-07-34.jpg', description: 'A comforting dry curry of potatoes and pointed gourd with a hint of roasted spices.' },
  { id: 'v8', category: 'veg', name: 'Aloo Matar', halfPrice: 150, fullPrice: 250, image: 'https://i.ibb.co/0pH4z6qy/Whats-App-Image-2026-04-04-at-21-18-51.jpg', description: 'Simple yet delicious combination of potatoes and green peas in a light, savory tomato gravy.' },
  { id: 'v9', category: 'veg', name: 'Palak Paneer', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/VcdG3yYv/Whats-App-Image-2026-04-04-at-21-18-52.jpg', description: 'Fresh paneer cubes in a smooth, vibrant spinach puree tempered with garlic and cumin.' },
  { id: 'v10', category: 'veg', name: 'Baigan Bari', halfPrice: 150, fullPrice: 250, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A traditional Mithila dish featuring eggplant and sun-dried lentil dumplings in a spiced gravy.' },
  { id: 'v11', category: 'veg', name: 'Aloo Kathal', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/9mbLr5dV/Whats-App-Image-2026-04-04-at-21-53-46.jpg', description: 'Tender jackfruit and potatoes cooked in a rich, meat-like gravy with robust Indian spices.' },
  { id: 'v12', category: 'veg', name: 'Kaju Keema', halfPrice: 350, fullPrice: 650, image: 'https://i.ibb.co/zHWNLm5k/Whats-App-Image-2026-04-04-at-21-56-27.jpg', description: 'A luxurious vegetarian mince made with finely chopped cashews and vegetables in a spicy masala.' },
  { id: 'v13', category: 'veg', name: 'Paneer Makhan', halfPrice: 250, fullPrice: 450, image: 'https://i.ibb.co/Mk9ynJc9/Whats-App-Image-2026-04-04-at-21-56-59.jpg', description: 'Creamy paneer makhani cooked with a touch of honey and finished with fresh cream.' },
  { id: 'v14', category: 'veg', name: 'Aloo Bhujia', halfPrice: 150, fullPrice: 250, image: 'https://i.ibb.co/VW0Cs9KK/Whats-App-Image-2026-04-04-at-20-18-05.jpg', description: 'Crispy, thinly sliced potato fries seasoned with turmeric and traditional Bihari spices.' },
  { id: 'v15', category: 'veg', name: 'Aloo Bhindi Masala', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/CKfxRPMb/Whats-App-Image-2026-04-04-at-21-12-57.jpg', description: 'A flavorful sauté of potatoes and okra with onions, tomatoes, and a blend of dry spices.' },
  { id: 'v16', category: 'veg', name: 'Aloo Bhindi Bhujia', halfPrice: 225, fullPrice: 400, image: 'https://i.ibb.co/Y7X8dZyL/Whats-App-Image-2026-04-04-at-20-18-33.jpg', description: 'A dry and crispy preparation of potatoes and okra, perfect as a side dish.' },
  { id: 'v17', category: 'veg', name: 'Aloo Shimla', halfPrice: 225, fullPrice: 450, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Potatoes and capsicum sautéed with cumin and coriander for a simple, earthy flavor.' },
  { id: 'v18', category: 'veg', name: 'Special Dal Fry', halfPrice: 180, fullPrice: 350, image: 'https://i.ibb.co/QFp1pb4X/Whats-App-Image-2026-04-04-at-12-48-47.jpg', description: 'Yellow lentils tempered with ghee, cumin, garlic, and red chilies for a smoky aroma.' },
  { id: 'v19', category: 'veg', name: 'Arhar Dal Tadka', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/QFp1pb4X/Whats-App-Image-2026-04-04-at-12-48-47.jpg', description: 'Pigeon pea lentils cooked to perfection and tempered with a classic tadka of mustard seeds and curry leaves.' },
  { id: 'v20', category: 'veg', name: 'Chana Dal Tadka', halfPrice: 180, fullPrice: 300, image: 'https://i.ibb.co/QFp1pb4X/Whats-App-Image-2026-04-04-at-12-48-47.jpg', description: 'Bengal gram lentils with a robust tempering of spices, providing a hearty and nutritious side.' },
  { id: 'v21', category: 'veg', name: 'Dal Makhani', halfPrice: 200, fullPrice: 400, image: 'https://i.ibb.co/yn1nLKQ5/Whats-App-Image-2026-04-04-at-20-24-29.jpg', description: 'Slow-cooked black lentils and kidney beans in a creamy, buttery gravy with a hint of smoke.' },
  { id: 'v22', category: 'veg', name: 'Kadhi Pakora', halfPrice: 180, fullPrice: 350, image: 'https://i.ibb.co/Z6wmpJLt/Whats-App-Image-2026-04-04-at-21-14-48.jpg', description: 'Tangy yogurt-based curry with crispy gram flour fritters, tempered with curry leaves and mustard seeds.' },
  { id: 'v23', category: 'veg', name: 'Tarua (Pakoda)', halfPrice: 400, fullPrice: 700, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Mithila style assorted vegetable fritters, deep-fried to a perfect golden crunch.' },
  { id: 'v24', category: 'veg', name: 'O Ka Sabji', halfPrice: 250, fullPrice: 450, image: 'https://i.ibb.co/wryYx6C4/Whats-App-Image-2026-04-04-at-21-55-37.jpg', description: 'A unique traditional vegetable preparation from Mithila, known for its earthy and savory notes.' },
  { id: 'v25', category: 'veg', name: 'Aloo Palak', halfPrice: 180, fullPrice: 320, image: 'https://i.ibb.co/vxpXX48P/Whats-App-Image-2026-04-04-at-21-54-32.jpg', description: 'A nutritious blend of potatoes and fresh spinach leaves cooked with mild spices and garlic.' },
  { id: 'v26', category: 'veg', name: 'Chole Masala', halfPrice: 225, fullPrice: 410, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Hearty chickpeas simmered in a spicy and tangy onion-tomato masala with a touch of amchoor.' },
  { id: 'v27', category: 'veg', name: 'Rajma Masala', halfPrice: 240, fullPrice: 425, image: 'https://i.ibb.co/yn1nLKQ5/Whats-App-Image-2026-04-04-at-20-24-29.jpg', description: 'Red kidney beans slow-cooked in a thick, flavorful gravy—a comforting North Indian classic.' },
  { id: 'v28', category: 'veg', name: 'Soya Chap Masala', halfPrice: 240, fullPrice: 410, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Protein-rich soya chaap pieces in a luscious, spicy tomato-onion gravy with aromatic herbs.' },
  { id: 'v29', category: 'veg', name: 'Aloo Pind', halfPrice: 120, fullPrice: 220, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A traditional potato preparation with a unique blend of local spices and a rustic texture.' },

  // Roti
  { id: 'r1', category: 'roti', name: 'Tawa Roti', price: 12, unit: 'Piece', image: 'https://i.ibb.co/bMQgxB3P/Whats-App-Image-2026-04-04-at-13-11-14.jpg', description: 'Soft and thin whole wheat flatbread cooked on a traditional tawa, served fresh and hot.' },
  { id: 'r2', category: 'roti', name: 'Tawa Butter Roti', price: 16, unit: 'Piece', image: 'https://i.ibb.co/bMQgxB3P/Whats-App-Image-2026-04-04-at-13-11-14.jpg', description: 'Our classic tawa roti brushed with a generous layer of pure desi ghee for extra flavor and softness.' },
  { id: 'r3', category: 'roti', name: 'Tandoori Roti', price: 15, unit: 'Piece', image: 'https://i.ibb.co/9HB7MMHs/Whats-App-Image-2026-04-04-at-13-27-01.jpg', description: 'Authentic clay oven-baked bread with a slightly smoky flavor and a perfect crisp-yet-soft texture.' },
  { id: 'r4', category: 'roti', name: 'Plain Paratha (Tikona)', price: 21, unit: 'Piece', image: 'https://i.ibb.co/BHgH3n7s/Whats-App-Image-2026-04-04-at-20-41-57.jpg', description: 'Flaky, multi-layered triangular paratha cooked with a touch of oil for a satisfying golden crunch.' },
  { id: 'r5', category: 'roti', name: 'Aloo Paratha', price: 50, unit: 'Piece', image: 'https://i.ibb.co/jkrdM7gn/Whats-App-Image-2026-04-04-at-13-17-20.jpg', description: 'Hearty whole wheat bread stuffed with a spiced mashed potato filling, served with a dollop of butter.' },
  { id: 'r6', category: 'roti', name: 'Payaz Paratha', price: 55, unit: 'Piece', image: 'https://images.unsplash.com/photo-1589113744320-99097500041d?auto=format&fit=crop&q=80&w=800', description: 'Deliciously stuffed paratha with finely chopped onions, green chilies, and a blend of savory spices.' },
  { id: 'r7', category: 'roti', name: 'Paneer Paratha', price: 80, unit: 'Piece', image: 'https://i.ibb.co/v6qZbfV5/Whats-App-Image-2026-04-04-at-20-45-23.jpg', description: 'A premium stuffed paratha filled with grated paneer, fresh coriander, and mild aromatic spices.' },
  { id: 'r8', category: 'roti', name: 'Puri', price: 10, unit: 'Piece', image: 'https://i.ibb.co/ccNm16vq/Whats-App-Image-2026-04-04-at-20-40-46.jpg', description: 'Golden, deep-fried puffed bread made from whole wheat flour, perfect with any curry or bhaji.' },
  { id: 'r9', category: 'roti', name: 'Kachori', price: 15, unit: 'Piece', image: 'https://i.ibb.co/jYTBm65/Whats-App-Image-2026-04-04-at-21-31-36.jpg', description: 'Crispy, deep-fried snack bread with a savory lentil or spiced potato stuffing, bursting with flavor.' },
  { id: 'r10', category: 'roti', name: 'Bedami Puri', price: 25, unit: 'Piece', image: 'https://i.ibb.co/tT7JGYhC/Whats-App-Image-2026-04-04-at-21-45-56.jpg', description: 'A specialty fried bread made with a mix of wheat and lentil flour, seasoned with fennel and cumin.' },
  { id: 'r11', category: 'roti', name: 'Laccha Paratha', price: 40, unit: 'Piece', image: 'https://i.ibb.co/9m11kVGJ/Whats-App-Image-2026-04-04-at-21-28-11.jpg', description: 'Beautifully layered and flaky flatbread cooked to a golden brown, offering a delightful texture in every bite.' },
  { id: 'r12', category: 'roti', name: 'Butter Naan', price: 60, unit: 'Piece', image: 'https://images.unsplash.com/photo-1589113744320-99097500041d?auto=format&fit=crop&q=80&w=800', description: 'Soft, leavened clay oven bread brushed with melted butter—the perfect companion for rich gravies.' },
  { id: 'r13', category: 'roti', name: 'Dal Puri', price: 40, unit: 'Piece', image: 'https://images.unsplash.com/photo-1589113744320-99097500041d?auto=format&fit=crop&q=80&w=800', description: 'Traditional deep-fried bread stuffed with a spiced chana dal filling, a festive favorite.' },
  { id: 'r14', category: 'roti', name: 'Matar Bharat Puri', price: 20, unit: 'Piece', image: 'https://i.ibb.co/F4zjfMbR/Whats-App-Image-2026-04-04-at-21-51-10.jpg', description: 'Delicate puri stuffed with a seasoned green pea mash, offering a sweet and savory surprise.' },

  // Rice
  { id: 'ri1', category: 'rice', name: 'Plain Boiled Rice', halfPrice: 100, fullPrice: 180, image: 'https://i.ibb.co/xqsmkqFG/Whats-App-Image-2026-04-04-at-21-49-10.jpg', description: 'Fluffy, long-grain basmati rice steamed to perfection—the ideal base for any curry.' },
  { id: 'ri2', category: 'rice', name: 'Fried Rice', halfPrice: 120, fullPrice: 200, image: 'https://i.ibb.co/hF0r66fd/Whats-App-Image-2026-04-04-at-21-49-49.jpg', description: 'Wok-tossed rice with a colorful mix of seasonal vegetables, seasoned with light soy and aromatic spices.' },
  { id: 'ri3', category: 'rice', name: 'Jeera Rice', halfPrice: 125, fullPrice: 220, image: 'https://i.ibb.co/jP3s8qVV/Whats-App-Image-2026-04-04-at-20-39-46.jpg', description: 'Fragrant basmati rice tempered with roasted cumin seeds and a touch of fresh coriander.' },
  { id: 'ri4', category: 'rice', name: 'Matar Pulao', halfPrice: 150, fullPrice: 275, image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&q=80&w=800', description: 'A delicate and aromatic rice preparation cooked with sweet green peas and whole garam masalas.' },
  { id: 'ri5', category: 'rice', name: 'Veg Biryani', halfPrice: 200, fullPrice: 350, image: 'https://i.ibb.co/1tgLQFzq/Whats-App-Image-2026-04-04-at-20-37-43.jpg', description: 'A fragrant masterpiece of basmati rice layered with spiced vegetables, saffron, and caramelized onions.' },
  { id: 'ri6', category: 'rice', name: 'Veg Biryani Family Pack', price: 550, image: 'https://i.ibb.co/1tgLQFzq/Whats-App-Image-2026-04-04-at-20-37-43.jpg', description: 'A large, celebratory portion of our fragrant veg biryani, served with raita and salan—perfect for sharing.' },
  { id: 'ri7', category: 'rice', name: 'Chicken Biryani', halfPrice: 250, fullPrice: 450, image: 'https://i.ibb.co/C5NKNPGx/Whats-App-Image-2026-04-04-at-20-36-00.jpg', description: 'Authentic dum-cooked biryani with succulent chicken pieces, aromatic spices, and long-grain basmati rice.' },
  { id: 'ri8', category: 'rice', name: 'Egg + Chicken Fry Rice', halfPrice: 300, fullPrice: 550, image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=800', description: 'A protein-packed combination of tender chicken and scrambled eggs tossed with flavorful fried rice.' },

  // Starters
  { id: 's1', category: 'starters', name: 'Chole Bhature (2 Piece)', price: 140, image: 'https://i.ibb.co/Xx2LXXP3/Whats-App-Image-2026-04-04-at-14-08-25.jpg', description: 'Two fluffy, deep-fried bhatures served with spicy, tangy chickpeas and a side of pickles and onions.' },
  { id: 's2', category: 'starters', name: 'Chole Bhature', price: 220, image: 'https://i.ibb.co/Xx2LXXP3/Whats-App-Image-2026-04-04-at-14-08-25.jpg', description: 'A larger serving of our signature chole bhature, perfect for a hearty breakfast or a satisfying lunch.' },
  { id: 's3', category: 'starters', name: 'Chura Fry with Peanut', price: 150, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Crispy fried flattened rice tossed with crunchy roasted peanuts, curry leaves, and a hint of green chili.' },
  { id: 's4', category: 'starters', name: 'Peanut with Moong Masala', price: 150, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A protein-rich snack of roasted peanuts and sprouted moong beans tossed with fresh onions, tomatoes, and lime.' },
  { id: 's5', category: 'starters', name: 'Chicken Kabab Fry', price: 80, unit: 'Piece', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800', description: 'Spiced chicken kabab pieces deep-fried to a golden crisp, served with tangy mint chutney.' },
  { id: 's6', category: 'starters', name: 'Chicken Fry', price: 160, unit: 'Plate', image: 'https://images.unsplash.com/photo-1562607394-59013bb10287?auto=format&fit=crop&q=80&w=800', description: 'A plate of our crispy, golden-brown fried chicken, marinated in a secret blend of zesty spices.' },
  { id: 's7', category: 'starters', name: 'Veg Chowmin', halfPrice: 120, fullPrice: 220, image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800', description: 'Indo-Chinese style stir-fried noodles with crunchy vegetables, soy sauce, and a hint of white pepper.' },
  { id: 's8', category: 'starters', name: 'Chicken Chowmin', halfPrice: 150, fullPrice: 280, image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800', description: 'Savory stir-fried noodles with tender chicken strips, fresh vegetables, and a bold blend of Chinese sauces.' },
  { id: 's9', category: 'starters', name: 'Egg + Chicken Chowmin', halfPrice: 200, fullPrice: 350, image: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&q=80&w=800', description: 'The ultimate noodle treat featuring both scrambled eggs and chicken bits for a protein-packed meal.' },
  { id: 's10', category: 'starters', name: 'Chicken Malai Tikka', halfPrice: 220, fullPrice: 380, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800', description: 'Creamy and mild chicken tikka marinated in a rich blend of cream, yogurt, and white pepper.' },
  { id: 's11', category: 'starters', name: 'French Fry', halfPrice: 220, fullPrice: 350, image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=800', description: 'Classic golden-brown potato fries, lightly salted and served hot with tomato ketchup.' },
  { id: 's12', category: 'starters', name: 'Chilly Potato (Full)', price: 75, image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&q=80&w=800', description: 'Crispy potato wedges tossed in a spicy and tangy chili sauce with onions and bell peppers.' },
  { id: 's13', category: 'starters', name: 'Pav Bhaji', price: 180, unit: 'Plate', image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=800', description: 'A spicy mashed vegetable curry served with soft, buttered bread rolls—a Mumbai street food favorite.' },
  { id: 's14', category: 'starters', name: 'Veg Momos (6 Piece)', price: 120, image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=800', description: 'Delicate steamed dumplings filled with a finely chopped vegetable mix, served with spicy red chutney.' },
  { id: 's15', category: 'starters', name: 'Veg Momos (12 Piece)', price: 225, image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=800', description: 'A dozen of our fresh steamed veg momos, perfect for sharing with friends and family.' },
  { id: 's16', category: 'starters', name: 'Chicken Momos (6 Piece)', price: 140, image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=800', description: 'Steamed dumplings with a juicy chicken filling, seasoned with ginger, garlic, and scallions.' },
  { id: 's17', category: 'starters', name: 'Chicken Momos (12 Piece)', price: 230, image: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?auto=format&fit=crop&q=80&w=800', description: 'A large portion of our flavorful chicken momos, served with our signature spicy dipping sauce.' },
  { id: 's18', category: 'starters', name: 'Special Paneer Pizza (Small)', price: 380, image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800', description: 'A mini pizza topped with spiced paneer cubes, crunchy vegetables, and a generous layer of mozzarella.' },
  { id: 's19', category: 'starters', name: 'Special Veg Sandwich', price: 140, unit: 'Piece', image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&q=80&w=800', description: 'A hearty sandwich layered with fresh vegetables, mint chutney, and a hint of sandwich masala.' },
  { id: 's20', category: 'starters', name: 'Burger', price: 80, unit: 'Piece', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800', description: 'A classic veg burger with a crispy potato patty, fresh lettuce, tomatoes, and our special burger sauce.' },
  { id: 's21', category: 'starters', name: 'Paneer Tikka', halfPrice: 200, fullPrice: 350, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800', description: 'Cubes of paneer marinated in a spicy yogurt blend and grilled to perfection with onions and peppers.' },
  { id: 's22', category: 'starters', name: 'Malai Paneer Tikka', halfPrice: 225, fullPrice: 410, image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800', description: 'A creamy version of paneer tikka, marinated in a rich mix of cream, cashews, and mild spices.' },

  // Thali
  { id: 't1', category: 'thali', name: 'Simple Veg Thali', price: 110, image: 'https://i.ibb.co/ynRRTkJg/Whats-App-Image-2026-04-04-at-20-47-33.jpg', description: 'A balanced meal featuring seasonal sabji, dal, rice, tawa roti, and fresh salad—perfect for a daily lunch.' },
  { id: 't2', category: 'thali', name: 'Special Veg Thali', price: 180, image: 'https://i.ibb.co/3yht8jZz/Whats-App-Image-2026-04-04-at-20-48-20.jpg', description: 'An elevated veg experience with a paneer specialty, choice of dal, pulao, butter roti, and a sweet treat.' },
  { id: 't3', category: 'thali', name: 'Special Chicken Thali', price: 250, image: 'https://i.ibb.co/qMDGyj2X/Whats-App-Image-2026-04-04-at-13-22-37.jpg', description: 'A hearty non-veg meal with our signature chicken curry, dal, rice, roti, and traditional accompaniments.' },
  { id: 't4', category: 'thali', name: 'Special Fish Thali', price: 300, image: 'https://i.ibb.co/qMDGyj2X/Whats-App-Image-2026-04-04-at-13-22-37.jpg', description: 'Authentic Mithila fish curry served with steamed rice, dal, and local vegetable sides for a complete experience.' },
  { id: 't5', category: 'thali', name: 'Special Mutton Thali', price: 350, image: 'https://i.ibb.co/qMDGyj2X/Whats-App-Image-2026-04-04-at-13-22-37.jpg', description: 'The ultimate non-veg feast featuring tender mutton curry, rice, roti, dal, and a side of fresh salad.' },
  { id: 't6', category: 'thali', name: 'With Sabji Thali', price: 100, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A simple and comforting thali with a choice of seasonal vegetable curry, rice, and roti.' },
  { id: 't7', category: 'thali', name: 'Family Veg Thali', price: 450, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A large, shared thali with multiple veg specialties, perfect for a family of three to four.' },

  // Sweets
  { id: 'sw1', category: 'sweets', name: 'Gulab Jamun', price: 35, unit: 'Piece', image: 'https://i.ibb.co/QjX5KDbt/Whats-App-Image-2026-04-04-at-20-12-22.jpg', description: 'Soft, melt-in-the-mouth khoya dumplings deep-fried and soaked in a fragrant cardamom sugar syrup.' },
  { id: 'sw2', category: 'sweets', name: 'Sponge Rasgulla', price: 50, unit: 'Piece', image: 'https://i.ibb.co/NgpbV8Dp/Whats-App-Image-2026-04-04-at-20-13-46.jpg', description: 'Light and airy cottage cheese balls simmered in a clear, sweet syrup—a classic Bengali delight.' },
  { id: 'sw3', category: 'sweets', name: 'Bihari Rasgulla', price: 35, unit: 'Piece', image: 'https://i.ibb.co/NgpbV8Dp/Whats-App-Image-2026-04-04-at-20-13-46.jpg', description: 'A traditional regional specialty, these rasgullas have a unique texture and a perfectly balanced sweetness.' },
  { id: 'sw4', category: 'sweets', name: 'Moong Dal Halwa', price: 100, unit: 'Bowl', image: 'https://i.ibb.co/pBFKPdzB/Whats-App-Image-2026-04-04-at-21-43-50.jpg', description: 'A rich and decadent dessert made with split yellow moong dal, pure desi ghee, and a generous garnish of nuts.' },
  { id: 'sw5', category: 'sweets', name: 'Suji Halwa', price: 80, unit: 'Bowl', image: 'https://i.ibb.co/YBfrWvR8/Whats-App-Image-2026-04-04-at-21-43-05.jpg', description: 'Classic semolina pudding cooked with ghee, sugar, and aromatic cardamom—a comforting sweet treat.' },
  { id: 'sw6', category: 'sweets', name: 'Sebai', price: 80, unit: 'Bowl', image: 'https://i.ibb.co/CKmrmPxG/Whats-App-Image-2026-04-04-at-21-40-47.jpg', description: 'Delicate vermicelli cooked in sweetened milk with a hint of saffron and crunchy dry fruits.' },
  { id: 'sw7', category: 'sweets', name: 'Makhana Kheer', price: 150, unit: 'Bowl', image: 'https://i.ibb.co/N2NgR00g/Whats-App-Image-2026-04-04-at-21-42-20.jpg', description: 'A nutritious and creamy pudding made with roasted fox nuts (makhana), milk, and a touch of sweetness.' },

  // Combo
  { id: 'co1', category: 'combo', name: 'Maach Bhaat', price: 350, image: 'https://i.ibb.co/Q3MyLbd5/Whats-App-Image-2026-04-04-at-20-56-22.jpg', description: 'The quintessential Mithila meal featuring fresh fish curry served with a generous portion of steamed rice.' },
  { id: 'co2', category: 'combo', name: 'Chicken Chawal', price: 300, image: 'https://i.ibb.co/Q3W0btmj/Whats-App-Image-2026-04-04-at-20-57-45.jpg', description: 'A satisfying combination of our spicy chicken curry and fluffy steamed rice—simple yet delicious.' },
  { id: 'co3', category: 'combo', name: 'Meat Bhaat', price: 400, image: 'https://i.ibb.co/tMcdjFc8/Whats-App-Image-2026-04-04-at-21-01-26.jpg', description: 'Tender mutton pieces in a rich gravy paired with perfectly cooked basmati rice for a royal experience.' },
  { id: 'co4', category: 'combo', name: 'Anda Curry with Rice', price: 300, image: 'https://i.ibb.co/5Xh0fRFS/Whats-App-Image-2026-04-04-at-21-20-56.jpg', description: 'Flavorful egg curry served with steamed rice, offering a comforting and protein-rich meal.' },

  // Mithilanchal
  { id: 'ms1', category: 'mithilanchal', name: 'Chura Dahi', price: 250, unit: 'Plate', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A traditional breakfast of flattened rice and fresh curd, often served with jaggery or sugar.' },
  { id: 'ms2', category: 'mithilanchal', name: 'Dal Pithi', price: 300, unit: 'Plate', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Whole wheat dumplings cooked in a spiced lentil soup—a wholesome and comforting regional specialty.' },
  { id: 'ms3', category: 'mithilanchal', name: 'Samosa Chaat', price: 250, unit: 'Plate', image: 'https://i.ibb.co/ymF5ynBh/Whats-App-Image-2026-04-04-at-21-33-04.jpg', description: 'Crushed crispy samosas topped with spicy chickpeas, tangy chutneys, yogurt, and crunchy sev.' },
  { id: 'ms4', category: 'mithilanchal', name: 'Chole Samosa', price: 120, image: 'https://i.ibb.co/ymF5ynBh/Whats-App-Image-2026-04-04-at-21-33-04.jpg', description: 'Golden-fried samosas served with a side of zesty chickpea curry and fresh onion rings.' },
  { id: 'ms5', category: 'mithilanchal', name: 'Murhi – Kachri with Aloo Chop', price: 125, unit: 'Plate', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A crunchy snack platter of puffed rice, lentil fritters, and spiced potato chops.' },
  { id: 'ms6', category: 'mithilanchal', name: 'Special Pakode', price: 140, unit: 'Plate', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'An assortment of seasonal vegetable fritters, deep-fried to perfection and served with tangy chutney.' },
  { id: 'ms7', category: 'mithilanchal', name: 'Bori + Bhat', price: 150, unit: 'Plate', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'Traditional sun-dried lentil dumplings (bori) served with steamed rice—a simple and authentic village meal.' },
  { id: 'ms8', category: 'mithilanchal', name: 'Small Fish Curry', price: 300, unit: 'Plate', image: 'https://i.ibb.co/RxD9gj6/Whats-App-Image-2026-04-04-at-08-47-21.jpg', description: 'A unique regional delicacy featuring small river fish cooked in a tangy and spicy mustard gravy.' },
  { id: 'ms9', category: 'mithilanchal', name: 'Litti Chokha (4 Piece)', price: 160, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'The pride of Bihar—roasted wheat balls stuffed with spiced sattu, served with mashed vegetables (chokha).' },
  { id: 'ms10', category: 'mithilanchal', name: 'Special Bihari Thali', price: 180, image: 'https://i.ibb.co/rK1Fhfjy/Whats-App-Image-2026-04-04-at-13-24-35.jpg', description: 'A complete regional feast featuring litti, chokha, dal, rice, and traditional seasonal specialties.' },

  // Special Thali
  { id: 'st1', category: 'special-thali', name: 'Special Mithilanchal Thali', price: 499, image: 'https://i.ibb.co/rK1Fhfjy/Whats-App-Image-2026-04-04-at-13-24-35.jpg', description: 'Our most premium thali offering a grand tour of Mithila cuisine with multiple curries, breads, and desserts.' },
  { id: 'st2', category: 'special-thali', name: 'Special Bulk Thali', price: 90, image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800', description: 'A value-packed meal including 3 rotis, rice, dal, seasonal sabji, and fresh salad—ideal for large orders.' },
];
